# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YshZ0vTLJq1lwolpQ2IM26F1TUqQ607-
"""

import streamlit as st
import pandas as pd
import joblib
import datetime
import numpy as np
import matplotlib.pyplot as plt

# 1. Page Configuration
st.set_page_config(
    page_title="UK Grid Analytics | Kamil Kehinde",
    page_icon="⚡",
    layout="wide"
)

# 2. Optimized Asset Loading
@st.cache_resource
def load_assets():
    # Load XGBoost Model
    model = joblib.load('gb_gen_time_only.pkl')

    # Load Validation Data (Oct 2025 - Feb 14, 2026)
    try:
        # Load only necessary columns to save Render RAM
        hist_data = pd.read_csv('TOTAL DEMAND GB.csv', usecols=['settlement_date', 'actual_mw'])

        # CLEANING: Handle ISO 8601 'T' and ensure timezones don't break the merge
        hist_data['settlement_date'] = pd.to_datetime(hist_data['settlement_date']).dt.tz_localize(None)
    except Exception as e:
        hist_data = pd.DataFrame()
        st.sidebar.warning(f"Note: Validation CSV not found or formatted incorrectly.")

    return model, hist_data

model, validation_df = load_assets()

# 3. Sidebar
with st.sidebar:
    st.header("👤 Lead Modeller")
    st.write("**Kamil Kehinde**")
    st.divider()
    st.info("Validation Window: Oct 1, 2025 – Feb 14, 2026")
    st.markdown("---")
    st.caption("A.I. Model: Univariate XGBoost")

# 4. Main UI
st.title("⚡ UK Electricity Generation Dashboard")
st.subheader("High-Fidelity Grid Forecasting & Residual Analysis")

# Date Selection
selected_range = st.date_input(
    "Select Analysis Range",
    value=(datetime.date(2026, 2, 10), datetime.date(2026, 2, 17))
)

if st.button("🚀 Run Analysis", use_container_width=True):
    if len(selected_range) == 2:
        start_d, end_d = selected_range

        # Create 30-min timestamp index for the selected range
        idx = pd.date_range(
            start=datetime.datetime.combine(start_d, datetime.time(0, 0)),
            end=datetime.datetime.combine(end_d, datetime.time(23, 30)),
            freq='30min'
        )

        # Build features for the model
        df_final = pd.DataFrame(index=idx)
        df_final['hour'] = df_final.index.hour
        df_final['dayofweek'] = df_final.index.dayofweek
        df_final['month'] = df_final.index.month
        df_final['year'] = df_final.index.year

        # Generate Predictions
        df_final['Forecast_MW'] = model.predict(df_final)
        df_final = df_final.reset_index().rename(columns={'index': 'timestamp'})

        # 5. Conditional Residual Logic (Merge Actuals)
        if not validation_df.empty:
            df_final = pd.merge(
                df_final,
                validation_df,
                left_on='timestamp',
                right_on='settlement_date',
                how='left'
            )
            # Residual = Actual - Predicted
            df_final['Residual_MW'] = df_final['actual_mw'] - df_final['Forecast_MW']
        else:
            df_final['actual_mw'] = np.nan
            df_final['Residual_MW'] = np.nan

        # 6. Performance Metrics
        m1, m2 = st.columns(2)
        m1.metric("Peak Forecasted Load", f"{df_final['Forecast_MW'].max():,.0f} MW")

        has_actuals = df_final['actual_mw'].notnull().any()
        if has_actuals:
            mae = df_final['Residual_MW'].abs().mean()
            m2.metric("Mean Absolute Error (MAE)", f"{mae:,.0f} MW", delta_color="inverse")
        else:
            m2.info("Future Forecast Mode: Actual data (residuals) not yet available.")

        # 7. Visualization
        fig, ax = plt.subplots(figsize=(12, 5))
        ax.plot(df_final['timestamp'], df_final['Forecast_MW'], label='Predicted Generation', color='#007acc', linewidth=2)

        if has_actuals:
            # Highlighting actuals and error gaps
            ax.scatter(df_final['timestamp'], df_final['actual_mw'], label='Actual Data (Oct-Feb)', color='orange', s=10, alpha=0.6)
            ax.fill_between(df_final['timestamp'], df_final['Forecast_MW'], df_final['actual_mw'], color='red', alpha=0.1, label='Model Residual')

        plt.xticks(rotation=45)
        ax.set_ylabel("Megawatts (MW)")
        ax.legend()
        st.pyplot(fig)

        # 8. Report Export
        st.download_button("📥 Export Analysis (CSV)", df_final.to_csv(index=False), "grid_analysis_report.csv")