# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19G_xR-Kvz8hHcMeFwQv4FuTn9wjlQKGC
"""

import streamlit as st
import pandas as pd
# Import your other necessary libraries (e.g., tensorflow, plotly, etc.)

# 1. SET PAGE CONFIGURATION - Must be the first Streamlit command
# This enables the 'Wide' mode to use the full width of the browser
st.set_page_config(
    page_title="UK Electricity Generation Forecast",
    page_icon="⚡",
    layout="wide"
)

# 2. SIDEBAR - Keeping your existing Lead Modeller profile
with st.sidebar:
    st.markdown("## 👤 Lead Modeller")
    st.markdown("### Kamil Kehinde")

    st.info("""
    **💡 Project Goal:** A.I. Forecasting Model for Great Britain’s
    System Operator Generation Mix.
    """)

    st.caption("Developed as part of a high-resolution Energy Case Study.")

# 3. MAIN CONTENT AREA
# Using a column layout to make the image 'bigger and better'
col_padding_left, col_main, col_padding_right = st.columns([1, 12, 1])

with col_main:
    # Title Section
    st.markdown("# ⚡ UK Electricity Generation Dashboard")

    # 4. ARCHITECTURE IMAGE - kamil_profile.png
    # use_container_width=True ensures it fills the 'col_main' space
    st.image(
        "kamil_profile.png",
        caption="System Architecture & Deep Learning Framework for GB Generation Forecasting",
        use_container_width=True
    )

    st.markdown("---")

    # 5. PROJECT DESCRIPTION (Corrected British English)
    st.write("""
    The UK electricity supply mix comprises Gas, Coal, Nuclear, Wind, Solar, Hydro, Biomass, and Imports.
    The system has undergone a significant transformation due to increasing **renewable penetration**,
    declining **coal usage**, and evolving **demand patterns**. Accurate short-term electricity
    generation forecasting is critical for:
    """)

    # Metrics or additional dashboard elements would follow here...
    # st.plotly_chart(your_forecast_fig, use_container_width=True)

# Footer
st.markdown("---")
st.caption("Data Source: NESO Data Bank Portal (2009–2026)")