# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YshZ0vTLJq1lwolpQ2IM26F1TUqQ607-
"""

import streamlit as st
import pandas as pd
import joblib
import datetime
import numpy as np
from PIL import Image

# 1. Page Configuration
st.set_page_config(
    page_title="UK Grid Analytics | Kamil Kehinde",
    page_icon="⚡",
    layout="wide"
)

# --- CUSTOM CSS FOR CENTERING ---
st.markdown("""
    <style>
    /* Centers the image container in the sidebar */
    [data-testid="stSidebarNav"] + div {
        display: flex;
        justify-content: center;
        padding-bottom: 20px;
    }
    .centered-img {
        display: block;
        margin-left: auto;
        margin-right: auto;
        border-radius: 50%; /* Optional: makes image circular */
    }
    </style>
    """, unsafe_allow_html=True)

# 2. Sidebar with Centered Image & Name
with st.sidebar:
    # Use columns to force centering if CSS is ignored
    col_side1, col_side2, col_side3 = st.columns([1, 3, 1])
    with col_side2:
        try:
            # Ensure this matches your GitHub file exactly: kamil_profile.jpeg
            profile_img = Image.open("kamil_profile.jpeg")
            st.image(profile_img, width=150)
        except FileNotFoundError:
            st.error("⚠️ 'kamil_profile.jpeg' not found on GitHub.")
            st.caption("Check file extension: .jpeg vs .jpg vs .png")

    st.markdown("<h2 style='text-align: center;'>Kamil Kehinde</h2>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: gray;'>Lead Energy Modeller</p>", unsafe_allow_html=True)
    st.divider()
    st.info("Univariate XGBoost Forecast Engine v2.5")

# 3. Model Loading
@st.cache_resource
def load_model():
    return joblib.load('gb_gen_time_only.pkl')

model = load_model()

# 4. Main UI
st.title("⚡ UK Electricity Generation Dashboard")
st.markdown("### Interactive Multi-Day Forecast & Grid Analytics")

# 5. Date Range Selection
st.divider()
start_default = datetime.date(2026, 2, 15)
end_default = start_default + datetime.timedelta(days=3)

selected_range = st.date_input(
    "📅 Select Forecast Horizon",
    value=(start_default, end_default),
    help="Select a range to see daily trends and total volume."
)

# 6. Prediction & Visuals
if len(selected_range) == 2:
    start_date, end_date = selected_range

    # Generate 30-min intervals
    predict_index = pd.date_range(
        start=datetime.datetime.combine(start_date, datetime.time(0, 0)),
        end=datetime.datetime.combine(end_date, datetime.time(23, 30)),
        freq='30T'
    )

    # Feature engineering
    predict_df = pd.DataFrame(index=predict_index)
    predict_df['hour'] = predict_df.index.hour
    predict_df['dayofweek'] = predict_df.index.dayofweek
    predict_df['month'] = predict_df.index.month
    predict_df['year'] = predict_df.index.year

    # Run Forecast
    predict_df['Forecast_MW'] = model.predict(predict_df)

    # Calculations
    avg_mw = predict_df['Forecast_MW'].mean()
    total_gwh = (predict_df['Forecast_MW'].sum() * 0.5) / 1000
    peak_mw = predict_df['Forecast_MW'].max()

    # KPI Display
    k1, k2, k3 = st.columns(3)
    k1.metric("Average Load", f"{avg_mw:,.0f} MW")
    k2.metric("Total Energy Volume", f"{total_gwh:,.2f} GWh")
    k3.metric("Predicted Peak", f"{peak_mw:,.0f} MW")

    # Plotting
    st.markdown(f"#### 📈 Generation Trend: {start_date} to {end_date}")
    st.line_chart(predict_df['Forecast_MW'], color="#FF4B4B")

    # Download
    st.download_button(
        "📥 Download Forecast (CSV)",
        data=predict_df.to_csv(),
        file_name=f"UK_Forecast_{start_date}.csv"
    )